#!/usr/bin/python3

import time
from wordle import *
from random import shuffle

def quit(match_word):
	w.guess(match_word)
	input(f"Solved:{match_word}! Press Enter to exit...")
	exit()

w = Wordle()
shuffle(w.open_guesses)
guess = (w.open_guesses[0])
w.guess(guess)
time.sleep(2)
ret = w.update(); print("Update return:", ret)
if ret:
	quit(w.words[0])
time.sleep(2)

shuffle(w.words)
guess = (w.words[0])
w.guess(guess)
time.sleep(2)
ret = w.update(); print("Update return:", ret)
if ret:
	quit(w.words[0])
time.sleep(2)

shuffle(w.words)
guess = (w.words[0])
w.guess(guess)
time.sleep(2)
ret = w.update(); print("Update return:", ret)
if ret:
	quit(w.words[0])
time.sleep(2)

shuffle(w.words)
guess = (w.words[0])
w.guess(guess)
time.sleep(2)
ret = w.update(); print("Update return:", ret)
if ret:
	quit(w.words[0])
time.sleep(2)

shuffle(w.words)
guess = (w.words[0])
w.guess(guess)
time.sleep(2)
ret = w.update(); print("Update return:", ret)
if ret:
	quit(w.words[0])
time.sleep(2)

shuffle(w.words)
guess = (w.words[0])
w.guess(guess)
time.sleep(2)
ret = w.update(); print("Update return:", ret)
if ret:
	quit(w.words[0])
time.sleep(2)
